### ISSUE TITLE
Hello, there was an error  when I tried to run the training classifier.

### ISSUE THREAD

**Issue by Hong409** [madeyoga/detect-bubble#1]
UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node vgg16/block1_conv1/Conv2D (defined at D:\Anaconda+opencv\lib\site-packages\tensorflow_core\python\framework\ops.py:1751) ]] [Op:__inference_distributed_function_1536]

I used tensorflow2.0.0 cuda10.0 cudnn 7.4.0.
Can you tell me your configuration environment if possible

**Comment by madeyoga** [comment]
Hai Hong409. 

Here is the exact version of tf I used for training & testing the classifier.
```
tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
tensorflow-gpu==2.3.0
tensorflow-gpu-estimator==2.3.0
```
- cuda 10.1 
- cudnn 7.6.5

#### Note
The classifier actually does not have a good performance (failed) when tested for object detection (detecting bubbles). 

So I changed the dataset, using [Manga109 Dataset](http://www.manga109.org/en/) and use [darknet](https://github.com/AlexeyAB/darknet) with YoloV3 configuration to detect the dialogue texts instead.

You can get the weights and the configuration here, and use the code example to detect the dialogue texts.
https://github.com/madeyoga/detect-bubble#darknet-yolov3-object-detection--manga109-dataset
